apiVersion: v1
kind: Pod
metadata:
  name: s3-reader-pod
  namespace: liang-eks
spec:
  # This ServiceAccount should be created and bound to an IAM role
  # using eksctl (IRSA lab). The pod just reuses that SA.
  serviceAccountName: s3-reader
  containers:
    - name: aws-cli
      image: amazon/aws-cli:2.15.0
      env:
        - name: AWS_REGION
          value: us-east-1
      command: ["sh", "-c"]
      args: ["sleep 3600"]
  restartPolicy: Never
