apiVersion: v1
kind: Pod
metadata:
  name: pvc-reader
  namespace: storage-lab
spec:
  containers:
    - name: reader
      image: busybox:1.36
      command: ["sh", "-c", "echo 'from gitops' > /data/from-git.txt; ls -l /data; sleep 3600"]
      volumeMounts:
        - name: data
          mountPath: /data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: demo-pvc